language: node_js
node_js:
  - 12 

services:
  - docker

install:
  - echo "nothing needs to be installed"

script:
  - docker --version
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag reverseproxy greengreengreen/reverseproxy:latest
  - docker tag udagram-api-feed greengreengreen/udagram-api-feed:latest
  - docker tag udagram-api-user greengreengreen/udagram-api-user:latest
  - docker tag udagram-frontend greengreengreen/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push greengreengreen/reverseproxy:latest
  - docker push greengreengreen/udagram-api-feed:latest
  - docker push greengreengreen/udagram-api-user:latest
  - docker push greengreengreen/udagram-frontend:latest
