language: node_js
node_js:
  - 12 

services:
  - docker

install:
  - echo "nothing needs to be installed"

script:
  - docker --version
  - docker build -t reverseproxy:latest ./udagram-reverseproxy
  - docker build -t udagram-api-feed:latest ./udagram-api-feed
  - docker build -t udagram-api-user:latest ./udagram-api-user
  - docker build -t udagram-frontend:local ./udagram-frontend

  - docker tag reverseproxy:latest greengreengreen/reverseproxy:latest
  - docker tag udagram-api-feed:latest greengreengreen/udagram-api-feed:latest
  - docker tag udagram-api-user:latest greengreengreen/udagram-api-user:latest
  - docker tag udagram-frontend:local greengreengreen/udagram-frontend:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push greengreengreen/reverseproxy:latest
  - docker push greengreengreen/udagram-api-feed:latest
  - docker push greengreengreen/udagram-api-user:latest
  - docker push greengreengreen/udagram-frontend:v4
